
[default_gamerule]
	hasFallAnimation = true
	#Range: 0 ~ 100
	weightPenalty = 100
	disapleEntityUI = false
	keepSkills = false
	doVanillaAttack = true
	globalStun = true
	stiffComboAttacks = true
	canSwitchCombat = true

[loot]
	#Range: -100 ~ 100
	skill_book_mob_drop_chance_modifier = 0
	#Range: -100 ~ 100
	skill_book_chest_drop_chance_modifier = 0

