name = "DawnCraft++"
version = "2.0.0-1.30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c684051da667a2fc763b498bcef033217d289ae8d85a056a41abbdb6342fd21c"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
