name = "DawnCraft++"
version = "1.0.1-1.28_f2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b0142b28c64525d11d8a5e2138b9a46af09bf4902d0a9eb07bdf9d68d8af696"

[versions]
forge = "40.2.10"
minecraft = "1.18.2"
